export const productos = [
    {
        id: 0,
        titulo: 'Miselio en petri',
        descripcion: 'Miselio colonizado en un muestrario de petri en APD',
        unidades: 6,
        categorias: 'miselio',
    },
    {
        id: 1,
        titulo: 'Grano miseliado',
        descripcion: 'Grano de trigo con miselio colonizado de ....',
        unidades: 3,
        categorias: 'miselio',
    },
    {
        id: 2,
        titulo: 'Bial de miselio',
        descripcion: 'Bial de 50 cc, con miselio en un ambiente liquido',
        unidades: 2,
        categorias: 'miselio',
    },
    {
        id: 3,
        titulo: 'Esporas',
        descripcion: 'Esporas deshidratadas esteriles, listas para rehidratar y colonizar.',
        unidades: 20,
        categorias: 'Kit de cultivo',
    },
    {
        id: 4,
        titulo: 'fibra de coco esteril',
        descripcion: 'Fibra de coco esperil y ya hidratada.',
        unidades: 50,
        categorias: 'sustrato',
    },
    {
        id: 5,
        titulo: 'vermiculita',
        descripcion: 'Vermiculita esteril y previamente hidratada',
        unidades: 50,
        categorias: 'sustrato',
    },
    {
        id: 6,
        titulo: 'perlita',
        descripcion: 'Perlita, retenedora de humedad para crear ambiente',
        unidades: 30,
        categorias: 'kits',
    },
    {
        id: 7,
        titulo: 'contenedor de 5litros',
        descripcion: 'es un contenedor plastico trasparente con orificion para una futura respiracion pasiva, capasidad de 5 litros.',
        unidades: 13,
        categorias: 'kit de cultivo',
    },
    {
        id: 8,
        titulo: 'bandeja de aluminio 2lts',
        descripcion: 'bandeja de aluminio de 2 litros para formar el bulk',
        unidades: 20,
        categorias: 'kits',
    },
    {
        id: 9,
        titulo: 'termometro',
        descripcion: 'Termometo en celcius para control de temperatura.',
        unidades: 10,
        categorias: 'kits',
    },
    {
        id: 10,
        titulo: 'calentador de agua',
        descripcion: 'calentador de agua sumergible.',
        unidades: 5,
        categorias: 'kits',
    },
    {
        id: 11,
        titulo: 'cajas de secado de producto',
        descripcion: 'cajas especializadas con ventilacion para la deshidratacion del producto.',
        unidades: 4,
        categorias: 'kits',
    },
    {
        id: 12,
        titulo: 'atomizadores',
        descripcion: 'atomizadores para preparaciones de desinfeccion.',
        unidades: 60,
        categorias: 'kits',
    },
    {
        id: 13,
        titulo: 'caja de petri',
        descripcion: 'caja de petri trasparente, material plastico.',
        unidades: 50,
        categorias: 'material esterilizado',
    },
]